### ISSUE TITLE
CI for unpaired Hedge's g on R and website not matching

### ISSUE THREAD

**Issue by heathium** [ACCLAB/dabestr#119]
Hi there,

Thank you again for making this great package available. I have found that the outcomes for the 95% CI of unpaired Hedge's g shared control comparisons have been consistently different between the web app and R (v0.3.9999), with R giving a slightly wider CI. For instance, for comparisons between groups A and B from the data attached in the csv file, the outcome from R is 0.205 [95CI  -0.833; 1.21] while the website gives 0.205 [95.0%CI -0.74, 1.18]. Could this be another potential bug with R? Which outcome would be the correct one?
[DATA.csv](https://github.com/ACCLAB/dabestr/files/7109407/DATA.csv)

Thanks in advance for your help.

**Comment by josesho** [comment]
Hi @heathium ,

The web app uses the Python package to produce the output, rather than the R package. 

Random number generation is used during the resampling for the CI computation. R and Python have different implementations of their random number generators, such that even setting the same seed will result in different outputs. See [here](https://gertjanvandenburg.com/blog/syncrng/) for more info. Thus, the output from dabestr and the web app will never match exactly. (If you want the results to match, consider using the Python package.)

Specifically for your dataset, B only has N=4, so the divergences between R and Python outputs will be greater. In our own testing, with N >= 10, the divergence between the CIs begins after the second decimal place.

Hope this helps,
Joses

**Comment by heathium** [comment]
Hi Joses,

Thank you so much for answering. I was just concerned seeing that the numbers did not match. I will not worry about it anymore and just use the CI calculated from R.
