### ISSUE TITLE
Multiple comparison adjustment / permutation t-test

### ISSUE THREAD

**Issue by Timmo83** [ACCLAB/dabestr#125]
Thanks for putting together this package! My question is around permutation t-tests which are on the web interface and I saw in a previous note we can look forward to in a new version of this package. Regardless I wanted to ask about the interpretation of permutation t-test values - when running multiple of these should they not be subject to adjustments for multiple comparison testing?

I notice that when I provide a subset of data from a larger dataset as a two sample dataset the permutation t-test value is identical to when the same comparison for those two groups is entered as a multi-two group or shared control plot. In the latter case I thought it would have to undergo correction for multiple comparisons?

Apologies if I have misunderstood the basis of this test.

**Comment by josesho** [comment]
Hi @Timmo83 ,Thank you for your question. We provide permutation _p_ values in our related [Python package](https://github.com/ACCLAB/DABEST-python) (which powers the webapp) in deference to biomedical reporting norms for results, which still relies heavily on null-hypothesis significance testing rather than an effect-size based approach that we and others have begun to advocate.

You are of course free to apply your own multiple testing correction to the permutation _p_ values, but this is a feature we do not see ourselves incorporating in the near futures.
