### ISSUE TITLE
bac CI not possible

### ISSUE THREAD

**Issue by davidbaniadam** [ACCLAB/dabestr#54]
Hello
Cool package. 
You write:
"All confidence intervals are bias-corrected and accelerated".
But I think this is a mistake. 
1) In your function `main.R` at line 333 you write:
` bootci <- boot::boot.ci(boot, conf = ci/100, type = c("perc", "bca"))`

2) I cannot find the formula for bca CI but you can see with this example that it does not work:

```
my_boot <- simpleboot::two.boot(rnorm(n = 100, mean = 1), rnorm(n = 151, mean = 3),  R= 100, FUN = mean)
boot::boot.ci(my_boot, conf = 0.95, type = "bca")
```

This is because the formula for  bca CI depends on `a` which in turn depends on `n`.  But we don't have a `n` in difference of means... We only have `n1` and `n2`.  But it is possible to create a "bias-corrected CI". 

My point is that I it is not possible to make a bca CI for difference in means (see slide 36 here http://users.stat.umn.edu/~helwig/notes/bootci-Notes.pdf)

**Comment by josesho** [comment]
Hi @davidbaniadam,

The problem seems to be that you set the number of bootstrap replicates (`R`) in `simpleboot::two.boot()` to too small a value for BCa computation.

Taking a look at the [Examples](https://www.rdocumentation.org/packages/boot/versions/1.3-23/topics/boot.ci) in the `boot::boot.ci()` documentation, the number of bootstrap replicates is set at 999.

The following code block should run without error:

```r
set.seed(12345)

my_boot <- simpleboot::two.boot(rnorm(n = 100, mean = 1), 
                                rnorm(n = 151, mean = 3),  
                                R = 999,
                                FUN = mean)

boot::boot.ci(my_boot, conf = 0.95, type = "bca")
```

to produce
```BOOTSTRAP CONFIDENCE INTERVAL CALCULATIONS
Based on 999 bootstrap replicates

CALL : 
boot::boot.ci(boot.out = my_boot, conf = 0.95, type = "bca")

Intervals : 
Level       BCa          
95%   (-2.069, -1.541 )  
Calculations and Intervals on Original Scale
```

For `dabestr`, the default number of bootstrap replicates is [5000](https://github.com/ACCLAB/dabestr/blob/a6b558f25169d1b3d98c3f9dc015c3c2d37e0727/R/main.R#L188), more than sufficient for BCa interval computation.

If you find that `boot::boot.ci` is in fact making an error, you could [contact the maintainer](https://cran.r-project.org/web/packages/boot/).
Thanks!
