### ISSUE TITLE
Allow control of ggplot object

### ISSUE THREAD

**Issue by matiasandina** [ACCLAB/dabestr#85]
Hi, thank you for such an awesome package. I don't know if this is possible but I would very much like to be able to do modifications on the plot produced by `dabestr` as I can do with `ggplot`. Some things are included as arguments to the plot function. But I would rather be able to do:

```
plot(unpaired_mean_diff, rawplot.ylabel = "y") +
 labs(title = "My awesome title here", 
         caption = "My caption here") +
 theme(legend.position = "bottom") # and other theme stuff here
```

Even though the returned object is of class `"gg" "ggplot"` I cannot interact normally with it (as in, add more layers).
For example, if I store a minimum `plot()` call into `p` and try:

```
p + theme(panel.border = element_rect(color="black"))
```

I get a blank plot

**Comment by josesho** [comment]
Hi,

Currently it is not possible to have a `ggplot2` style syntax, because the final output composed of two separately created ggplot2 objects, stitched together by [cowplot](https://wilkelab.org/cowplot/)'s [`plot_grid()`](https://wilkelab.org/cowplot/reference/plot_grid.html) function. 

So from a ggplot2 perspective, doing

```r
plot(unpaired_mean_diff, rawplot.ylabel = "y") +
 labs(title = "My awesome title here", 
         caption = "My caption here")
```

would not work on the output of `plot_grid()`, because 

I do not know if it is at all possible to have what you propose. We might have to create our own [`ggproto`](https://ggplot2.tidyverse.org/reference/ggproto.html) object for estimation plots, but have two aligned axes, AFAIK, would require some heavy-duty [`grid`](https://stat.ethz.ch/R-manual/R-devel/library/graphics/html/grid.html) hacking...

I might be wrong! If you figure out how to have that easy ggplot2 syntax, happy to receive a PR from you. We'll have to close this for now, unfortunately....

Thanks,
Joses
