### ISSUE TITLE
Difficulty plotting based on levels

### ISSUE THREAD

**Issue by sophschwartz** [ACCLAB/dabestr#91]
Error in `levels<-`(`*tmp*`, value = as.character(levels)) : 
  factor level [4] is duplicated

Dataframe:
[Z-Score_Alpha_Right_Temporal_GroupbyMeasurement.xlsx](https://github.com/ACCLAB/dabestr/files/5042212/Z-Score_Alpha_Right_Temporal_GroupbyMeasurement.xlsx)

Code: 
Z_Score_Alpha_Right_Temporal <- read_excel("(https://github.com/ACCLAB/dabestr/files/5042212/Z-Score_Alpha_Right_Temporal_GroupbyMeasurement.xlsx")
multi.two.group.unpaired <- 
  Z_Score_Alpha_Right_Temporal %>%
  dabest(Group, Measurement, 
         idx = list(c("ASDV", "TD"), 
                    c("ASDMLV", "TD"),
                    c("ASDMLV", "ASDV")),
         paired = FALSE)
multi.two.group.unpaired.meandiff <- mean_diff(multi.two.group.unpaired)
plot(multi.two.group.unpaired.meandiff, color.column = Group)

The group appears to have 3 levels based on:
multi.two.group.unpaired.meandiff[[1]]$Group <- factor(multi.two.group.unpaired.meandiff[[1]]$Group, levels = unique(multi.two.group.unpaired.meandiff[[1]]$Group), ordered=FALSE)

**Comment by josesho** [comment]
Hi @sophschwartz ,

The error arises because you have repeated groups in your `idx`, as seen in your example:

```r
idx = list(c("ASDV", "TD"),
              c("ASDMLV", "TD"),
              c("ASDMLV", "ASDV"))
```

From the earliest stages of designing `dabestr`,  we [decided not to allow plotting of the same group twice](https://github.com/ACCLAB/DABEST-python/issues/43)—both an aesthetic decision and a statistical one: we don't want viewers (and the plotters themselves) to unintentionally perceive the two instances of `ASDMLV`, for instance in this case.

The UI/UX, however, can be improved: when loading the data into `dabestr`, and when calling the `mean_diff` function. (In fact, the effect size functions do allow computation of the effect sizes!!)

On a broader and related topic: there have been several requests ([here](https://groups.google.com/g/estimationstats/c/W5_d65uYOa0), [here](https://github.com/ACCLAB/DABEST-python/issues?q=is%3Aissue+is%3Aclosed+ANOVA+), and [here](https://groups.google.com/g/estimationstats/c/W5_d65uYOa0)) to perform ANOVA in DABEST: comparing all groups to all other groups. What we consider best practice is to use [delta-delta plots](https://twitter.com/TheNewStats/status/1141933404939870210?s=20). These are still being developed, unfortunately.

You can use [estimationstats.com](http://www.estimationstats.com/#/analyze/multi) to produce the plot you desire as well, but the second appearance of a repeated group will be colored differently (and given an additional prefix): you can fix this in any vector graphics software.

Hope this helps!
Joses
